import { IElementData } from '~/types';

export const ELEMENTS: IElementData[] = [
  {
    atomicNumber: 1,
    symbol: 'H',
    name: 'Hydrogen',
    atomicMass: 1.008,
    period: 1,
    group: 1,
    block: 's',
    electronConfiguration: '1s1',
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    name: 'Helium',
    atomicMass: 4.002602,
    period: 1,
    group: 18,
    block: 's',
    electronConfiguration: '1s2',
  },
  {
    atomicNumber: 3,
    symbol: 'Li',
    name: 'Lithium',
    atomicMass: 6.94,
    period: 2,
    group: 1,
    block: 's',
    electronConfiguration: '1s2 2s1',
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    name: 'Beryllium',
    atomicMass: 9.0122,
    period: 2,
    group: 2,
    block: 's',
    electronConfiguration: '1s2 2s2',
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    name: 'Boron',
    atomicMass: 10.81,
    period: 2,
    group: 13,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p1',
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    name: 'Carbon',
    atomicMass: 12.011,
    period: 2,
    group: 14,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p2',
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    name: 'Nitrogen',
    atomicMass: 14.007,
    period: 2,
    group: 15,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p3',
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    name: 'Oxygen',
    atomicMass: 15.999,
    period: 2,
    group: 16,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p4',
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    name: 'Fluorine',
    atomicMass: 18.998403163,
    period: 2,
    group: 17,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p5',
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    name: 'Neon',
    atomicMass: 20.1797,
    period: 2,
    group: 18,
    block: 'p',
    electronConfiguration: '1s2 2s2 2p6',
  },
  {
    atomicNumber: 11,
    symbol: 'Na',
    name: 'Sodium',
    atomicMass: 22.98976928,
    period: 3,
    group: 1,
    block: 's',
    electronConfiguration: '[Ne] 3s1',
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    atomicMass: 24.305,
    period: 3,
    group: 2,
    block: 's',
    electronConfiguration: '[Ne] 3s2',
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    name: 'Aluminum',
    atomicMass: 26.9815385,
    period: 3,
    group: 13,
    block: 'p',
    electronConfiguration: '[Ne] 3s2 3p1',
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    name: 'Silicon',
    atomicMass: 28.085,
    period: 3,
    group: 14,
    block: 'p',
    electronConfiguration: '[Ne] 3s2 3p2',
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    name: 'Phosphorus',
    atomicMass: 30.973761998,
    period: 3,
    group: 15,
    block: 'p',
    electronConfiguration: '[Ne] 3s2 3p3',
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    name: 'Sulfur',
    atomicMass: 32.06,
    period: 3,
    group: 16,
    block: 'p',
    electronConfiguration: '[Ne] 3s2 3p4',
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    atomicMass: 35.45,
    period: 3,
    group: 17,
    block: 'p',
    electronConfiguration: '[Ne] 3s2 3p5',
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    name: 'Argon',
    atomicMass: 39.948,
    period: 3,
    group: 18,
    block: 'p',
    electronConfiguration: '[Ne] 3s2 3p6',
  },
  {
    atomicNumber: 19,
    symbol: 'K',
    name: 'Potassium',
    atomicMass: 39.0983,
    period: 4,
    group: 1,
    block: 's',
    electronConfiguration: '[Ar] 4s1',
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    name: 'Calcium',
    atomicMass: 40.078,
    period: 4,
    group: 2,
    block: 's',
    electronConfiguration: '[Ar] 4s2',
  },
  {
    atomicNumber: 21,
    symbol: 'Sc',
    name: 'Scandium',
    atomicMass: 44.955908,
    period: 4,
    group: 3,
    block: 'd',
    electronConfiguration: '[Ar] 3d1 4s2',
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    name: 'Titanium',
    atomicMass: 47.867,
    period: 4,
    group: 4,
    block: 'd',
    electronConfiguration: '[Ar] 3d2 4s2',
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    name: 'Vanadium',
    atomicMass: 50.9415,
    period: 4,
    group: 5,
    block: 'd',
    electronConfiguration: '[Ar] 3d3 4s2',
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    name: 'Chromium',
    atomicMass: 51.9961,
    period: 4,
    group: 6,
    block: 'd',
    electronConfiguration: '[Ar] 3d5 4s1',
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    name: 'Manganese',
    atomicMass: 54.938044,
    period: 4,
    group: 7,
    block: 'd',
    electronConfiguration: '[Ar] 3d5 4s2',
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    name: 'Iron',
    atomicMass: 55.845,
    period: 4,
    group: 8,
    block: 'd',
    electronConfiguration: '[Ar] 3d6 4s2',
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    name: 'Cobalt',
    atomicMass: 58.933194,
    period: 4,
    group: 9,
    block: 'd',
    electronConfiguration: '[Ar] 3d7 4s2',
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    name: 'Nickel',
    atomicMass: 58.6934,
    period: 4,
    group: 10,
    block: 'd',
    electronConfiguration: '[Ar] 3d8 4s2',
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    name: 'Copper',
    atomicMass: 63.546,
    period: 4,
    group: 11,
    block: 'd',
    electronConfiguration: '[Ar] 3d10 4s1',
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    name: 'Zinc',
    atomicMass: 65.38,
    period: 4,
    group: 12,
    block: 'd',
    electronConfiguration: '[Ar] 3d10 4s2',
  },
  {
    atomicNumber: 31,
    symbol: 'Ga',
    name: 'Gallium',
    atomicMass: 69.723,
    period: 4,
    group: 13,
    block: 'p',
    electronConfiguration: '[Ar] 3d10 4s2 4p1',
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    name: 'Germanium',
    atomicMass: 72.63,
    period: 4,
    group: 14,
    block: 'p',
    electronConfiguration: '[Ar] 3d10 4s2 4p2',
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    name: 'Arsenic',
    atomicMass: 74.921595,
    period: 4,
    group: 15,
    block: 'p',
    electronConfiguration: '[Ar] 3d10 4s2 4p3',
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    name: 'Selenium',
    atomicMass: 78.971,
    period: 4,
    group: 16,
    block: 'p',
    electronConfiguration: '[Ar] 3d10 4s2 4p4',
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    name: 'Bromine',
    atomicMass: 79.904,
    period: 4,
    group: 17,
    block: 'p',
    electronConfiguration: '[Ar] 3d10 4s2 4p5',
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    name: 'Krypton',
    atomicMass: 83.798,
    period: 4,
    group: 18,
    block: 'p',
    electronConfiguration: '[Ar] 3d10 4s2 4p6',
  },
  {
    atomicNumber: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    atomicMass: 85.4678,
    period: 5,
    group: 1,
    block: 's',
    electronConfiguration: '[Kr] 5s1',
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    name: 'Strontium',
    atomicMass: 87.62,
    period: 5,
    group: 2,
    block: 's',
    electronConfiguration: '[Kr] 5s2',
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    name: 'Yttrium',
    atomicMass: 88.90584,
    period: 5,
    group: 3,
    block: 'd',
    electronConfiguration: '[Kr] 4d1 5s2',
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    atomicMass: 91.224,
    period: 5,
    group: 4,
    block: 'd',
    electronConfiguration: '[Kr] 4d2 5s2',
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    name: 'Niobium',
    atomicMass: 92.90637,
    period: 5,
    group: 5,
    block: 'd',
    electronConfiguration: '[Kr] 4d4 5s1',
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    atomicMass: 95.95,
    period: 5,
    group: 6,
    block: 'd',
    electronConfiguration: '[Kr] 4d5 5s1',
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    name: 'Technetium',
    atomicMass: 98,
    period: 5,
    group: 7,
    block: 'd',
    electronConfiguration: '[Kr] 4d5 5s2',
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    atomicMass: 101.07,
    period: 5,
    group: 8,
    block: 'd',
    electronConfiguration: '[Kr] 4d7 5s1',
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    atomicMass: 102.9055,
    period: 5,
    group: 9,
    block: 'd',
    electronConfiguration: '[Kr] 4d8 5s1',
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    name: 'Palladium',
    atomicMass: 106.42,
    period: 5,
    group: 10,
    block: 'd',
    electronConfiguration: '[Kr] 4d10',
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    name: 'Silver',
    atomicMass: 107.8682,
    period: 5,
    group: 11,
    block: 'd',
    electronConfiguration: '[Kr] 4d10 5s1',
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    atomicMass: 112.414,
    period: 5,
    group: 12,
    block: 'd',
    electronConfiguration: '[Kr] 4d10 5s2',
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    name: 'Indium',
    atomicMass: 114.818,
    period: 5,
    group: 13,
    block: 'p',
    electronConfiguration: '[Kr] 4d10 5s2 5p1',
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    name: 'Tin',
    atomicMass: 118.71,
    period: 5,
    group: 14,
    block: 'p',
    electronConfiguration: '[Kr] 4d10 5s2 5p2',
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    name: 'Antimony',
    atomicMass: 121.76,
    period: 5,
    group: 15,
    block: 'p',
    electronConfiguration: '[Kr] 4d10 5s2 5p3',
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    name: 'Tellurium',
    atomicMass: 127.6,
    period: 5,
    group: 16,
    block: 'p',
    electronConfiguration: '[Kr] 4d10 5s2 5p4',
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    name: 'Iodine',
    atomicMass: 126.90447,
    period: 5,
    group: 17,
    block: 'p',
    electronConfiguration: '[Kr] 4d10 5s2 5p5',
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    name: 'Xenon',
    atomicMass: 131.293,
    period: 5,
    group: 18,
    block: 'p',
    electronConfiguration: '[Kr] 4d10 5s2 5p6',
  },
  {
    atomicNumber: 55,
    symbol: 'Cs',
    name: 'Cesium',
    atomicMass: 132.90545196,
    period: 6,
    group: 1,
    block: 's',
    electronConfiguration: '[Xe] 6s1',
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    name: 'Barium',
    atomicMass: 137.327,
    period: 6,
    group: 2,
    block: 's',
    electronConfiguration: '[Xe] 6s2',
  },
  {
    atomicNumber: 57,
    symbol: 'La',
    name: 'Lanthanum',
    atomicMass: 138.90547,
    period: 6,
    group: 3,
    block: 'd',
    electronConfiguration: '[Xe] 5d1 6s2',
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    name: 'Cerium',
    atomicMass: 140.116,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f1 5d1 6s2',
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    atomicMass: 140.90766,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f3 6s2',
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    atomicMass: 144.242,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f4 6s2',
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    name: 'Promethium',
    atomicMass: 145,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f5 6s2',
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    name: 'Samarium',
    atomicMass: 150.36,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f6 6s2',
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    name: 'Europium',
    atomicMass: 151.964,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f7 6s2',
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    atomicMass: 157.25,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f7 5d1 6s2',
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    name: 'Terbium',
    atomicMass: 158.92535,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f9 6s2',
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    atomicMass: 162.5,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f10 6s2',
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    name: 'Holmium',
    atomicMass: 164.93033,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f11 6s2',
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    name: 'Erbium',
    atomicMass: 167.259,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f12 6s2',
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    name: 'Thulium',
    atomicMass: 168.93422,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f13 6s2',
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    atomicMass: 173.045,
    period: 6,
    group: null,
    block: 'f',
    electronConfiguration: '[Xe] 4f14 6s2',
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    atomicMass: 174.9668,
    period: 6,
    group: 3,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d1 6s2',
  },
  {
    atomicNumber: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    atomicMass: 178.49,
    period: 6,
    group: 4,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d2 6s2',
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    atomicMass: 180.94788,
    period: 6,
    group: 5,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d3 6s2',
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    name: 'Tungsten',
    atomicMass: 183.84,
    period: 6,
    group: 6,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d4 6s2',
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    name: 'Rhenium',
    atomicMass: 186.207,
    period: 6,
    group: 7,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d5 6s2',
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    name: 'Osmium',
    atomicMass: 190.23,
    period: 6,
    group: 8,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d6 6s2',
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    name: 'Iridium',
    atomicMass: 192.217,
    period: 6,
    group: 9,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d7 6s2',
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    name: 'Platinum',
    atomicMass: 195.084,
    period: 6,
    group: 10,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d9 6s1',
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    name: 'Gold',
    atomicMass: 196.966569,
    period: 6,
    group: 11,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d10 6s1',
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    name: 'Mercury',
    atomicMass: 200.592,
    period: 6,
    group: 12,
    block: 'd',
    electronConfiguration: '[Xe] 4f14 5d10 6s2',
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    name: 'Thallium',
    atomicMass: 204.38,
    period: 6,
    group: 13,
    block: 'p',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p1',
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    name: 'Lead',
    atomicMass: 207.2,
    period: 6,
    group: 14,
    block: 'p',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p2',
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    atomicMass: 208.9804,
    period: 6,
    group: 15,
    block: 'p',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p3',
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    name: 'Polonium',
    atomicMass: 209,
    period: 6,
    group: 16,
    block: 'p',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p4',
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    name: 'Astatine',
    atomicMass: 210,
    period: 6,
    group: 17,
    block: 'p',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p5',
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    name: 'Radon',
    atomicMass: 222,
    period: 6,
    group: 18,
    block: 'p',
    electronConfiguration: '[Xe] 4f14 5d10 6s2 6p6',
  },
  {
    atomicNumber: 87,
    symbol: 'Fr',
    name: 'Francium',
    atomicMass: 223,
    period: 7,
    group: 1,
    block: 's',
    electronConfiguration: '[Rn] 7s1',
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    name: 'Radium',
    atomicMass: 226,
    period: 7,
    group: 2,
    block: 's',
    electronConfiguration: '[Rn] 7s2',
  },
  {
    atomicNumber: 89,
    symbol: 'Ac',
    name: 'Actinium',
    atomicMass: 227,
    period: 7,
    group: 3,
    block: 'd',
    electronConfiguration: '[Rn] 6d1 7s2',
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    name: 'Thorium',
    atomicMass: 232.0377,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 6d2 7s2',
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    atomicMass: 231.03588,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f2 6d1 7s2',
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    name: 'Uranium',
    atomicMass: 238.02891,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f3 6d1 7s2',
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    name: 'Neptunium',
    atomicMass: 237,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f4 6d1 7s2',
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    atomicMass: 244,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f6 7s2',
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    name: 'Americium',
    atomicMass: 243,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f7 7s2',
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    name: 'Curium',
    atomicMass: 247,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f7 6d1 7s2',
  },
  {
    atomicNumber: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    atomicMass: 247,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f9 7s2',
  },
  {
    atomicNumber: 98,
    symbol: 'Cf',
    name: 'Californium',
    atomicMass: 251,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f10 7s2',
  },
  {
    atomicNumber: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    atomicMass: 252,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f11 7s2',
  },
  {
    atomicNumber: 100,
    symbol: 'Fm',
    name: 'Fermium',
    atomicMass: 257,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f12 7s2',
  },
  {
    atomicNumber: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    atomicMass: 258,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f13 7s2',
  },
  {
    atomicNumber: 102,
    symbol: 'No',
    name: 'Nobelium',
    atomicMass: 259,
    period: 7,
    group: null,
    block: 'f',
    electronConfiguration: '[Rn] 5f14 7s2',
  },
  {
    atomicNumber: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    atomicMass: 266,
    period: 7,
    group: 3,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 7s2 7p1',
  },
  {
    atomicNumber: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    atomicMass: 267,
    period: 7,
    group: 4,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d2 7s2',
  },
  {
    atomicNumber: 105,
    symbol: 'Db',
    name: 'Dubnium',
    atomicMass: 268,
    period: 7,
    group: 5,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d3 7s2',
  },
  {
    atomicNumber: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    atomicMass: 269,
    period: 7,
    group: 6,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d4 7s2',
  },
  {
    atomicNumber: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    atomicMass: 270,
    period: 7,
    group: 7,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d5 7s2',
  },
  {
    atomicNumber: 108,
    symbol: 'Hs',
    name: 'Hassium',
    atomicMass: 270,
    period: 7,
    group: 8,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d6 7s2',
  },
  {
    atomicNumber: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    atomicMass: 278,
    period: 7,
    group: 9,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d7 7s2',
  },
  {
    atomicNumber: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    atomicMass: 281,
    period: 7,
    group: 10,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d9 7s1',
  },
  {
    atomicNumber: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    atomicMass: 282,
    period: 7,
    group: 11,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d10 7s1',
  },
  {
    atomicNumber: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    atomicMass: 285,
    period: 7,
    group: 12,
    block: 'd',
    electronConfiguration: '[Rn] 5f14 6d10 7s2',
  },
  {
    atomicNumber: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    atomicMass: 286,
    period: 7,
    group: 13,
    block: 'p',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p1',
  },
  {
    atomicNumber: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    atomicMass: 289,
    period: 7,
    group: 14,
    block: 'p',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p2',
  },
  {
    atomicNumber: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    atomicMass: 290,
    period: 7,
    group: 15,
    block: 'p',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p3',
  },
  {
    atomicNumber: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    atomicMass: 293,
    period: 7,
    group: 16,
    block: 'p',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p4',
  },
  {
    atomicNumber: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    atomicMass: 294,
    period: 7,
    group: 17,
    block: 'p',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p5',
  },
  {
    atomicNumber: 118,
    symbol: 'Og',
    name: 'Oganesson',
    atomicMass: 294,
    period: 7,
    group: 18,
    block: 'p',
    electronConfiguration: '[Rn] 5f14 6d10 7s2 7p6',
  },
];
